baseURL = 'https://www.aerovolumes.com/'
languageCode = 'en-us'
title = 'Aero Volumes'
theme = 'hyde'

[Menus]
  main = [
      {Name = "Get the data", URL = "https://rapidapi.com/CharlieHenry/api/aerovolumes", Weight=0},
      {Name = "Twitter", URL = "https://x.com/aerovolumes", Weight=1},
      {Name = "Bluesky", URL = "https://bsky.app/profile/aerovolumes.com", Weight=2}
  ]

[params]
  description = "TSA volume trends for every airport in America"
  themeColor = "theme-base-0d"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
    	unsafe = true